# Generated by Django 2.2.24 on 2021-06-09 15:46

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NucleusData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_param_json', django_mysql.models.JSONField(default=dict)),
                ('null_json', django_mysql.models.JSONField(default=dict, null=True)),
                ('default_json', django_mysql.models.JSONField(default=list)),
                ('null_n_default_json', django_mysql.models.JSONField(default=list, null=True)),
                ('no_param_txt', models.TextField()),
                ('null_txt', models.TextField(null=True)),
                ('default_txt', models.TextField(default='')),
                ('null_n_default_txt', models.TextField(default='', null=True)),
                ('null_default_blank_txt', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
